INSERT INTO `openeyes`.`ophcocorrespondence_letter_macro` (`name`, `body`, `cc_patient`, `display_order`, `site_id`, `cc_doctor`, `cc_drss`, `recipient_id`, `letter_type_id`) VALUES ('Test All codes', 'age (Patient age) ::: [age]
dmt (Type of diabetes mellitus) ::: [dmt]
edl (Left eye episode diagnosis) ::: [edl]
edr (Right eye episode diagnosis) ::: [edr]
epc (Consultant for the episode of the current subspecialty) ::: [epc]
epd (Principal diagnosis for episode) ::: [epd]
eps (Principal side for episode) ::: [eps]
epv (Service for the episode of the current subspecialty) ::: [epv]
obj (Patient as object (him/her)) ::: [obj]
pos (Patient possessive (his/hers)) ::: [pos]
pro (Patient pronoun (he/she)) ::: [pro]
sdl (List of secondary diagnoses for patient) ::: [sdl]
sub (Patient as subject (man/woman)) ::: [sub]
syd (Systemic diagnoses) ::: [syd]
rxt (Last Biometry target refraction) ::: [rxt]
alg (List all patients assigned allergies) ::: [alg]
aod (List of Ophthalmic Diagnoses) ::: [aod]
eld (Get Date of Last Examination Date) ::: [eld]
gom (Glaucoma Overall Management Plan from latest Examination) ::: [gom]
ilp (IOL Power from last cataract operation note) ::: [ilp]
ilt (IOL type from last cataract Operation Note) ::: [ilt]
loe (Operated Eye (left/right) from last operation note) ::: [loe]
pna (Get Full Patient Name) ::: [pna]
pnf (Get Patient First Name) ::: [pnf]
pnl (Get Patient Last Name) ::: [pnl]
pnt (Get Patient Title) ::: [pnt]
por (Pre-Op Refraction - both eyes) ::: [por]
pov (Pre-Op Visual Acuity - both eyes) ::: [pov]
adl (Adnexal comorbidity in the left eye) ::: [adl]
adr (Adnexal comorbidity in the right eye) ::: [adr]
aka (List of patients allergies) ::: [aka]
asl (Anterior segment findings in the left eye) ::: [asl]
asp (Anterior segment findings in the principal eye) ::: [asp]
asr (Anterior segment findings in the right eye) ::: [asr]
bvd (Best visual acuity in both eyes with date (Latest recorded within the last 3 weeks)) ::: [bvd]
ccl (Examination CCT value for left eye) ::: [ccl]
ccr (Examination CCT value for right eye) ::: [ccr]
cct (Examination CCT values for principal eye) ::: [cct]
cld (Clinical left retinopathy) ::: [cld]
clm (Clinical left maculopathy) ::: [clm]
cnl (Central corneal thickness, left eye reading no units) ::: [cnl]
cnr (Central corneal thickness, right eye reading no units) ::: [cnr]
con (Conclusion) ::: [con]
crd (Clinical right retinopathy) ::: [crd]
crm (Clinical left maculopathy) ::: [crm]
csm (Cataract Surgical Management) ::: [csm]
cta (Central corneal thickness, abbreviated form) ::: [cta]
edf (Examination diagnoses and findings) ::: [edf]
fup (Follow up period) ::: [fup]
glr (Get the most recent Glaucoma Risk value for the patient) ::: [glr]
hpc (History of presenting complaint) ::: [hpc]
imb (Visual acuity findings from latest examination) ::: [imb]
imf (Injection management findings from latest examination) ::: [imf]
iml (Injection Management Complex diagnosis for left eye from Examination) ::: [iml]
imr (Injection Management Complex diagnosis for right eye from Examination) ::: [imr]
iof (Intraocular pressure, both eyes, first reading only) ::: [iof]
iol (Intraocular pressure, left eye reading no units) ::: [iol]
ior (Intraocular pressure, right eye reading no units) ::: [ior]
iot (Intraocular pressure values returned in a tabular format) ::: [iot]
ipa (Intraocular pressure, abbreviated form) ::: [ipa]
ipb (Intraocular pressure in both eyes) ::: [ipb]
ipl (Intraocular pressure in the left eye) ::: [ipl]
ipp (Intraocular pressure in the principal eye) ::: [ipp]
ipr (Intraocular pressure in the right eye) ::: [ipr]
lmc (Laser management comments) ::: [lmc]
lmf (Laser management findings from latest examination) ::: [lmf]
lmp (Laser management plan) ::: [lmp]
lvd (Best visual acuity in the left eye with date (Latest recorded within the last 3 weeks)) ::: [lvd]
man (Management) ::: [man]
nlm (NSC left maculopathy) ::: [nlm]
nlr (NSC left retinopathy) ::: [nlr]
nrm (NSC right maculopathy) ::: [nrm]
nrr (NSC right retinopathy) ::: [nrr]
occ (Clinic Outcome comments from Examination) ::: [occ]
ode (Outcome details from latest Examination) ::: [ode]
opd (Examination Optic Disc description field value for principal eye) ::: [opd]
psl (Posterior pole findings in the left eye) ::: [psl]
psp (Posterior pole findings in the principal eye) ::: [psp]
psr (Posterior pole findings in the right eye) ::: [psr]
pvd (Best visual acuity in the principle eye with date (Latest recorded within the last 3 weeks)) ::: [pvd]
rvd (Best visual acuity in the right eye with date (Latest recorded within the last 3 weeks)) ::: [rvd]
tcl (Central SFT for left eye from Examination) ::: [tcl]
tcr (Central SFT for right eye from Examination) ::: [tcr]
tml (Maximim CRT for left eye from Examination) ::: [tml]
tmr (Maximim CRT for right eye from Examination) ::: [tmr]
vaf (Visual acuity findings from latest examination) ::: [vaf]
vbb (Best visual acuity in both eyes) ::: [vbb]
vbl (Best visual acuity in the left eye) ::: [vbl]
vbp (Best visual acuity in the principal eye) ::: [vbp]
vbr (Best visual acuity in the right eye) ::: [vbr]
vhp (Examination Van Herick grading value for principal eye) ::: [vhp]
idb (Treatment drug both eyes) ::: [idb]
idl (Intravitreal injection drug for left eye) ::: [idl]
idr (Intravitreal injection drug for right eye) ::: [idr]
inb (Treatment number both eyes) ::: [inb]
inl (Intravitreal injection number for left eye) ::: [inl]
inr (Intravitreal injection number for right eye) ::: [inr]
pid (Post injection examination drops) ::: [pid]
loc (Last operation peri-operative complications) ::: [loc]
lod (Last Operation Date) ::: [lod]
lol (Last Operation Location) ::: [lol]
los (Last Operation Surgeon Name) ::: [los]
opc (Last operation comments) ::: [opc]
opm (Last Operation Incision Meridian) ::: [opm]
opr (Operations carried out) ::: [opr]
ops (Operations carried out with SNOMED terms) ::: [ops]
opv (Last operation details) ::: [opv]
poi (Last operation post op instructions) ::: [poi]
puc (Patient Unique Code for portal) ::: [puc]
rxp (Last Operation Predicted Refraction) ::: [rxp]
adm (Admission date for most recent booking) ::: [adm]
obd (The latest operation booking diagnosis) ::: [obd]
opf (All Operation Bookings WITHOUT Operation Notes) ::: [opf]
opl (Operations listed for) ::: [opl]
pre (Prescription) ::: [pre]
tdb (Therapy application diagnosis for both eyes) ::: [tdb]
tdl (Therapy application diagnosis for left eye) ::: [tdl]
tdr (Therapy application diagnosis for right eye) ::: [tdr]
ttb (Therapy application treatment for both eyes) ::: [ttb]
ttl (Therapy application treatment for left eye) ::: [ttl]
ttr (Therapy application treatment for right eye) ::: [ttr]', '0', '1', '1', '0', '0', '1', '4');
